inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/SpaceBeforeBrackets:
  Enabled: false

# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBrackets.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBrackets: space, no_space
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

# Configuration parameters: EnforcedStyle.
# SupportedStyles: space, no_space
Layout/SpaceInsideParens:
  EnforcedStyle: space

Layout/SpaceInsideRangeLiteral:
  Enabled: false

# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBrackets.
# SupportedStyles: space, no_space
# SupportedStylesForEmptyBrackets: space, no_space
Layout/SpaceInsideReferenceBrackets:
  EnforcedStyle: space

Lint/DuplicateBranch:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  CountAsOne: [ array, hash, heredoc, method_call ]

Metrics/ClassLength:
  CountComments: false
  CountAsOne: [ array, hash, heredoc, method_call ]

Metrics/MethodLength:
  CountComments: false
  CountAsOne: [ array, hash, heredoc, method_call ]

Style/FrozenStringLiteralComment:
  Enabled: false

# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Configuration parameters: EnforcedStyle, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Enabled: false
#  EnforcedStyle: slashes
#  AllowInnerSlashes: true

Style/SafeNavigation:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

# Configuration parameters: .
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Configuration parameters: MinSize, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: brackets
